# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import joblet_pb2 as proto_dot_joblet__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in proto/joblet_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class JobServiceStub(object):
    """Main service for running jobs"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunJob = channel.unary_unary(
            "/joblet.JobService/RunJob",
            request_serializer=proto_dot_joblet__pb2.RunJobRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.RunJobResponse.FromString,
            _registered_method=True,
        )
        self.GetJobStatus = channel.unary_unary(
            "/joblet.JobService/GetJobStatus",
            request_serializer=proto_dot_joblet__pb2.GetJobStatusRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.GetJobStatusResponse.FromString,
            _registered_method=True,
        )
        self.StopJob = channel.unary_unary(
            "/joblet.JobService/StopJob",
            request_serializer=proto_dot_joblet__pb2.StopJobRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.StopJobResponse.FromString,
            _registered_method=True,
        )
        self.CancelJob = channel.unary_unary(
            "/joblet.JobService/CancelJob",
            request_serializer=proto_dot_joblet__pb2.CancelJobRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.CancelJobResponse.FromString,
            _registered_method=True,
        )
        self.DeleteJob = channel.unary_unary(
            "/joblet.JobService/DeleteJob",
            request_serializer=proto_dot_joblet__pb2.DeleteJobRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.DeleteJobResponse.FromString,
            _registered_method=True,
        )
        self.DeleteAllJobs = channel.unary_unary(
            "/joblet.JobService/DeleteAllJobs",
            request_serializer=proto_dot_joblet__pb2.DeleteAllJobsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.DeleteAllJobsResponse.FromString,
            _registered_method=True,
        )
        self.GetJobLogs = channel.unary_stream(
            "/joblet.JobService/GetJobLogs",
            request_serializer=proto_dot_joblet__pb2.GetJobLogsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.DataChunk.FromString,
            _registered_method=True,
        )
        self.ListJobs = channel.unary_unary(
            "/joblet.JobService/ListJobs",
            request_serializer=proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.Jobs.FromString,
            _registered_method=True,
        )
        self.StreamJobMetrics = channel.unary_stream(
            "/joblet.JobService/StreamJobMetrics",
            request_serializer=proto_dot_joblet__pb2.StreamJobMetricsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.JobMetricsEvent.FromString,
            _registered_method=True,
        )
        self.GetJobMetrics = channel.unary_stream(
            "/joblet.JobService/GetJobMetrics",
            request_serializer=proto_dot_joblet__pb2.GetJobMetricsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.JobMetricsEvent.FromString,
            _registered_method=True,
        )
        self.StreamJobTelematics = channel.unary_stream(
            "/joblet.JobService/StreamJobTelematics",
            request_serializer=proto_dot_joblet__pb2.StreamJobTelematicsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.TelematicsEvent.FromString,
            _registered_method=True,
        )
        self.GetJobTelematics = channel.unary_stream(
            "/joblet.JobService/GetJobTelematics",
            request_serializer=proto_dot_joblet__pb2.GetJobTelematicsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.TelematicsEvent.FromString,
            _registered_method=True,
        )


class JobServiceServicer(object):
    """Main service for running jobs"""

    def RunJob(self, request, context):
        """Job operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteAllJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetJobLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamJobMetrics(self, request, context):
        """Job Metrics (resource usage from cgroups - sampled every 5s)
        Stream live metrics for a running job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetJobMetrics(self, request, context):
        """Get historical metrics for a completed job"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamJobTelematics(self, request, context):
        """Job Telematics (eBPF security events - event-driven)
        Stream live telematics events for a running job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetJobTelematics(self, request, context):
        """Get historical telematics events for a completed job"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunJob": grpc.unary_unary_rpc_method_handler(
            servicer.RunJob,
            request_deserializer=proto_dot_joblet__pb2.RunJobRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.RunJobResponse.SerializeToString,
        ),
        "GetJobStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetJobStatus,
            request_deserializer=proto_dot_joblet__pb2.GetJobStatusRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.GetJobStatusResponse.SerializeToString,
        ),
        "StopJob": grpc.unary_unary_rpc_method_handler(
            servicer.StopJob,
            request_deserializer=proto_dot_joblet__pb2.StopJobRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.StopJobResponse.SerializeToString,
        ),
        "CancelJob": grpc.unary_unary_rpc_method_handler(
            servicer.CancelJob,
            request_deserializer=proto_dot_joblet__pb2.CancelJobRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.CancelJobResponse.SerializeToString,
        ),
        "DeleteJob": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteJob,
            request_deserializer=proto_dot_joblet__pb2.DeleteJobRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.DeleteJobResponse.SerializeToString,
        ),
        "DeleteAllJobs": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteAllJobs,
            request_deserializer=proto_dot_joblet__pb2.DeleteAllJobsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.DeleteAllJobsResponse.SerializeToString,
        ),
        "GetJobLogs": grpc.unary_stream_rpc_method_handler(
            servicer.GetJobLogs,
            request_deserializer=proto_dot_joblet__pb2.GetJobLogsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.DataChunk.SerializeToString,
        ),
        "ListJobs": grpc.unary_unary_rpc_method_handler(
            servicer.ListJobs,
            request_deserializer=proto_dot_joblet__pb2.EmptyRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.Jobs.SerializeToString,
        ),
        "StreamJobMetrics": grpc.unary_stream_rpc_method_handler(
            servicer.StreamJobMetrics,
            request_deserializer=proto_dot_joblet__pb2.StreamJobMetricsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.JobMetricsEvent.SerializeToString,
        ),
        "GetJobMetrics": grpc.unary_stream_rpc_method_handler(
            servicer.GetJobMetrics,
            request_deserializer=proto_dot_joblet__pb2.GetJobMetricsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.JobMetricsEvent.SerializeToString,
        ),
        "StreamJobTelematics": grpc.unary_stream_rpc_method_handler(
            servicer.StreamJobTelematics,
            request_deserializer=proto_dot_joblet__pb2.StreamJobTelematicsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.TelematicsEvent.SerializeToString,
        ),
        "GetJobTelematics": grpc.unary_stream_rpc_method_handler(
            servicer.GetJobTelematics,
            request_deserializer=proto_dot_joblet__pb2.GetJobTelematicsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.TelematicsEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "joblet.JobService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("joblet.JobService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Main service for running jobs"""

    @staticmethod
    def RunJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/RunJob",
            proto_dot_joblet__pb2.RunJobRequest.SerializeToString,
            proto_dot_joblet__pb2.RunJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetJobStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/GetJobStatus",
            proto_dot_joblet__pb2.GetJobStatusRequest.SerializeToString,
            proto_dot_joblet__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/StopJob",
            proto_dot_joblet__pb2.StopJobRequest.SerializeToString,
            proto_dot_joblet__pb2.StopJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/CancelJob",
            proto_dot_joblet__pb2.CancelJobRequest.SerializeToString,
            proto_dot_joblet__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/DeleteJob",
            proto_dot_joblet__pb2.DeleteJobRequest.SerializeToString,
            proto_dot_joblet__pb2.DeleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteAllJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/DeleteAllJobs",
            proto_dot_joblet__pb2.DeleteAllJobsRequest.SerializeToString,
            proto_dot_joblet__pb2.DeleteAllJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetJobLogs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.JobService/GetJobLogs",
            proto_dot_joblet__pb2.GetJobLogsRequest.SerializeToString,
            proto_dot_joblet__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListJobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.JobService/ListJobs",
            proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            proto_dot_joblet__pb2.Jobs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamJobMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.JobService/StreamJobMetrics",
            proto_dot_joblet__pb2.StreamJobMetricsRequest.SerializeToString,
            proto_dot_joblet__pb2.JobMetricsEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetJobMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.JobService/GetJobMetrics",
            proto_dot_joblet__pb2.GetJobMetricsRequest.SerializeToString,
            proto_dot_joblet__pb2.JobMetricsEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamJobTelematics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.JobService/StreamJobTelematics",
            proto_dot_joblet__pb2.StreamJobTelematicsRequest.SerializeToString,
            proto_dot_joblet__pb2.TelematicsEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetJobTelematics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.JobService/GetJobTelematics",
            proto_dot_joblet__pb2.GetJobTelematicsRequest.SerializeToString,
            proto_dot_joblet__pb2.TelematicsEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class NetworkServiceStub(object):
    """Network service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNetwork = channel.unary_unary(
            "/joblet.NetworkService/CreateNetwork",
            request_serializer=proto_dot_joblet__pb2.CreateNetworkRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.CreateNetworkResponse.FromString,
            _registered_method=True,
        )
        self.ListNetworks = channel.unary_unary(
            "/joblet.NetworkService/ListNetworks",
            request_serializer=proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.Networks.FromString,
            _registered_method=True,
        )
        self.RemoveNetwork = channel.unary_unary(
            "/joblet.NetworkService/RemoveNetwork",
            request_serializer=proto_dot_joblet__pb2.RemoveNetworkRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.RemoveNetworkResponse.FromString,
            _registered_method=True,
        )


class NetworkServiceServicer(object):
    """Network service"""

    def CreateNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListNetworks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateNetwork": grpc.unary_unary_rpc_method_handler(
            servicer.CreateNetwork,
            request_deserializer=proto_dot_joblet__pb2.CreateNetworkRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.CreateNetworkResponse.SerializeToString,
        ),
        "ListNetworks": grpc.unary_unary_rpc_method_handler(
            servicer.ListNetworks,
            request_deserializer=proto_dot_joblet__pb2.EmptyRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.Networks.SerializeToString,
        ),
        "RemoveNetwork": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveNetwork,
            request_deserializer=proto_dot_joblet__pb2.RemoveNetworkRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.RemoveNetworkResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "joblet.NetworkService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("joblet.NetworkService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NetworkService(object):
    """Network service"""

    @staticmethod
    def CreateNetwork(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.NetworkService/CreateNetwork",
            proto_dot_joblet__pb2.CreateNetworkRequest.SerializeToString,
            proto_dot_joblet__pb2.CreateNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListNetworks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.NetworkService/ListNetworks",
            proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            proto_dot_joblet__pb2.Networks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveNetwork(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.NetworkService/RemoveNetwork",
            proto_dot_joblet__pb2.RemoveNetworkRequest.SerializeToString,
            proto_dot_joblet__pb2.RemoveNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class VolumeServiceStub(object):
    """Volume service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVolume = channel.unary_unary(
            "/joblet.VolumeService/CreateVolume",
            request_serializer=proto_dot_joblet__pb2.CreateVolumeRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.CreateVolumeResponse.FromString,
            _registered_method=True,
        )
        self.ListVolumes = channel.unary_unary(
            "/joblet.VolumeService/ListVolumes",
            request_serializer=proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.Volumes.FromString,
            _registered_method=True,
        )
        self.RemoveVolume = channel.unary_unary(
            "/joblet.VolumeService/RemoveVolume",
            request_serializer=proto_dot_joblet__pb2.RemoveVolumeRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.RemoveVolumeResponse.FromString,
            _registered_method=True,
        )


class VolumeServiceServicer(object):
    """Volume service"""

    def CreateVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListVolumes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VolumeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateVolume": grpc.unary_unary_rpc_method_handler(
            servicer.CreateVolume,
            request_deserializer=proto_dot_joblet__pb2.CreateVolumeRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.CreateVolumeResponse.SerializeToString,
        ),
        "ListVolumes": grpc.unary_unary_rpc_method_handler(
            servicer.ListVolumes,
            request_deserializer=proto_dot_joblet__pb2.EmptyRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.Volumes.SerializeToString,
        ),
        "RemoveVolume": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveVolume,
            request_deserializer=proto_dot_joblet__pb2.RemoveVolumeRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.RemoveVolumeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "joblet.VolumeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("joblet.VolumeService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class VolumeService(object):
    """Volume service"""

    @staticmethod
    def CreateVolume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.VolumeService/CreateVolume",
            proto_dot_joblet__pb2.CreateVolumeRequest.SerializeToString,
            proto_dot_joblet__pb2.CreateVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListVolumes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.VolumeService/ListVolumes",
            proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            proto_dot_joblet__pb2.Volumes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveVolume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.VolumeService/RemoveVolume",
            proto_dot_joblet__pb2.RemoveVolumeRequest.SerializeToString,
            proto_dot_joblet__pb2.RemoveVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class MonitoringServiceStub(object):
    """Monitoring service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
            "/joblet.MonitoringService/GetSystemStatus",
            request_serializer=proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.SystemStatusResponse.FromString,
            _registered_method=True,
        )
        self.StreamSystemMetrics = channel.unary_stream(
            "/joblet.MonitoringService/StreamSystemMetrics",
            request_serializer=proto_dot_joblet__pb2.StreamMetricsRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.SystemMetricsResponse.FromString,
            _registered_method=True,
        )


class MonitoringServiceServicer(object):
    """Monitoring service"""

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamSystemMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSystemStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemStatus,
            request_deserializer=proto_dot_joblet__pb2.EmptyRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.SystemStatusResponse.SerializeToString,
        ),
        "StreamSystemMetrics": grpc.unary_stream_rpc_method_handler(
            servicer.StreamSystemMetrics,
            request_deserializer=proto_dot_joblet__pb2.StreamMetricsRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.SystemMetricsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "joblet.MonitoringService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "joblet.MonitoringService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MonitoringService(object):
    """Monitoring service"""

    @staticmethod
    def GetSystemStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.MonitoringService/GetSystemStatus",
            proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            proto_dot_joblet__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamSystemMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.MonitoringService/StreamSystemMetrics",
            proto_dot_joblet__pb2.StreamMetricsRequest.SerializeToString,
            proto_dot_joblet__pb2.SystemMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class RuntimeServiceStub(object):
    """Runtime service for managing execution environments"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRuntimes = channel.unary_unary(
            "/joblet.RuntimeService/ListRuntimes",
            request_serializer=proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.ListRuntimesResponse.FromString,
            _registered_method=True,
        )
        self.GetRuntimeInfo = channel.unary_unary(
            "/joblet.RuntimeService/GetRuntimeInfo",
            request_serializer=proto_dot_joblet__pb2.GetRuntimeInfoRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.GetRuntimeInfoResponse.FromString,
            _registered_method=True,
        )
        self.TestRuntime = channel.unary_unary(
            "/joblet.RuntimeService/TestRuntime",
            request_serializer=proto_dot_joblet__pb2.TestRuntimeRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.TestRuntimeResponse.FromString,
            _registered_method=True,
        )
        self.RemoveRuntime = channel.unary_unary(
            "/joblet.RuntimeService/RemoveRuntime",
            request_serializer=proto_dot_joblet__pb2.RemoveRuntimeRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.RemoveRuntimeResponse.FromString,
            _registered_method=True,
        )
        self.BuildRuntime = channel.unary_stream(
            "/joblet.RuntimeService/BuildRuntime",
            request_serializer=proto_dot_joblet__pb2.BuildRuntimeRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.BuildRuntimeProgress.FromString,
            _registered_method=True,
        )
        self.ValidateRuntimeYAML = channel.unary_unary(
            "/joblet.RuntimeService/ValidateRuntimeYAML",
            request_serializer=proto_dot_joblet__pb2.ValidateRuntimeYAMLRequest.SerializeToString,
            response_deserializer=proto_dot_joblet__pb2.ValidateRuntimeYAMLResponse.FromString,
            _registered_method=True,
        )


class RuntimeServiceServicer(object):
    """Runtime service for managing execution environments"""

    def ListRuntimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRuntimeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TestRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BuildRuntime(self, request, context):
        """BuildRuntime builds a runtime from a YAML specification
        The build process runs on the server and streams progress back to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateRuntimeYAML(self, request, context):
        """ValidateRuntimeYAML validates a runtime YAML specification without building"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListRuntimes": grpc.unary_unary_rpc_method_handler(
            servicer.ListRuntimes,
            request_deserializer=proto_dot_joblet__pb2.EmptyRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.ListRuntimesResponse.SerializeToString,
        ),
        "GetRuntimeInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetRuntimeInfo,
            request_deserializer=proto_dot_joblet__pb2.GetRuntimeInfoRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.GetRuntimeInfoResponse.SerializeToString,
        ),
        "TestRuntime": grpc.unary_unary_rpc_method_handler(
            servicer.TestRuntime,
            request_deserializer=proto_dot_joblet__pb2.TestRuntimeRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.TestRuntimeResponse.SerializeToString,
        ),
        "RemoveRuntime": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveRuntime,
            request_deserializer=proto_dot_joblet__pb2.RemoveRuntimeRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.RemoveRuntimeResponse.SerializeToString,
        ),
        "BuildRuntime": grpc.unary_stream_rpc_method_handler(
            servicer.BuildRuntime,
            request_deserializer=proto_dot_joblet__pb2.BuildRuntimeRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.BuildRuntimeProgress.SerializeToString,
        ),
        "ValidateRuntimeYAML": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateRuntimeYAML,
            request_deserializer=proto_dot_joblet__pb2.ValidateRuntimeYAMLRequest.FromString,
            response_serializer=proto_dot_joblet__pb2.ValidateRuntimeYAMLResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "joblet.RuntimeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("joblet.RuntimeService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Runtime service for managing execution environments"""

    @staticmethod
    def ListRuntimes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.RuntimeService/ListRuntimes",
            proto_dot_joblet__pb2.EmptyRequest.SerializeToString,
            proto_dot_joblet__pb2.ListRuntimesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetRuntimeInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.RuntimeService/GetRuntimeInfo",
            proto_dot_joblet__pb2.GetRuntimeInfoRequest.SerializeToString,
            proto_dot_joblet__pb2.GetRuntimeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TestRuntime(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.RuntimeService/TestRuntime",
            proto_dot_joblet__pb2.TestRuntimeRequest.SerializeToString,
            proto_dot_joblet__pb2.TestRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveRuntime(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.RuntimeService/RemoveRuntime",
            proto_dot_joblet__pb2.RemoveRuntimeRequest.SerializeToString,
            proto_dot_joblet__pb2.RemoveRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BuildRuntime(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/joblet.RuntimeService/BuildRuntime",
            proto_dot_joblet__pb2.BuildRuntimeRequest.SerializeToString,
            proto_dot_joblet__pb2.BuildRuntimeProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateRuntimeYAML(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/joblet.RuntimeService/ValidateRuntimeYAML",
            proto_dot_joblet__pb2.ValidateRuntimeYAMLRequest.SerializeToString,
            proto_dot_joblet__pb2.ValidateRuntimeYAMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
