name: Dependency Updates

on:
  schedule:
    # Check for dependency updates weekly on Mondays at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update dependencies
        run: |
          # Update main dependencies
          pip-compile --upgrade setup.py
          
          # Update dev dependencies
          if [ -f requirements-dev.in ]; then
            pip-compile --upgrade requirements-dev.in
          fi

      - name: Check for security vulnerabilities
        run: |
          pip install safety
          safety check --json --output safety-report.json || true

      - name: Create update branch
        run: |
          BRANCH_NAME="dependency-update-$(date +%Y-%m-%d)"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet; then
            echo "No dependency updates available"
            echo "updates_available=false" >> $GITHUB_ENV
          else
            echo "Dependency updates available"
            echo "updates_available=true" >> $GITHUB_ENV
            git checkout -b "$BRANCH_NAME"
          fi

      - name: Commit changes
        if: env.updates_available == 'true'
        run: |
          git add .
          git commit -m "chore: update dependencies
          
          Auto-generated dependency update"
          git push origin "${{ env.branch_name }}"

      - name: Create Pull Request
        if: env.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
          title: "🔄 Update dependencies"
          body: |
            ## Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated Python package dependencies
            - Checked for security vulnerabilities
            
            ### Security Check
            See attached safety report for any security advisories.
            
            ### Testing
            - [ ] CI tests pass
            - [ ] No breaking changes introduced
            
            ---
            🤖 *This PR was automatically created by the dependency-update workflow*
          labels: |
            dependencies
            automation